Add some workarounds in README
irreleph4nt/mkinitcpio-bluetooth pull request #9
Opened 2021-10-26 16:52 UTC by DucNg

Add instruction for workarounds if HOOK doesn't work out of the box.

2021-10-26 17:50 UTC, irreleph4nt requested changes
Thank you for your contribution. With a few easy fixes I am happy to merge this.

2021-10-26 17:50 UTC, irreleph4nt commented on README.md
> +    **Exemple:**
Can you please correct spelling to English? i.e. "Example", not "Exemple"

2021-10-26 17:50 UTC, irreleph4nt commented on README.md
> +**Exemple:**
Same as above, please correct spelling.

2021-10-26 19:33 UTC, DucNg commented
Of course, here you go!

2021-10-27 00:21 UTC, irreleph4nt approved these changes
Thank you, looks good to merge to me.

2021-10-27 00:21 UTC, merged